# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               InteractWithStats
tagline:             ''
description:         'Statistics should be the most exciting class students take in college. Let us deliver that!'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              The creator, Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
