---
theme: jekyll-theme-minimal
title: Kelly Findley
author:
  name: "Kelly Findley"
  avatar: "/images/casual-photo.jpg"
  bio: "I teach Statistics!."
  location: "University of Illinois at Urbana-Champaign"
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      author_profile: true
      sidebar:
        nav: "docs"
---
